Weather/Models/Client.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Weather.Models
{
	//https://developer.forecast.io/docs/v2

	//https://api.forecast.io/forecast/APIKEY/LATITUDE,LONGITUDE,TIME

	/*
	APIKEY should be your Dark Sky API key. LATITUDE and LONGITUDE should be the geographic coordinates of a location in decimal degrees. (Please note that the base domain for this API request is api.forecast.io, not api.darkskyapp.com.)

	The response will be a JSON-formatted object with the following properties defined:

	latitude: The requested latitude.
	longitude: The requested longitude.
	timezone: The IANA timezone name for the requested location (e.g. America/New_York). This is the timezone used for text forecast summaries and for determining the exact start time of daily data points. (Developers are advised to rely on local system settings rather than this value if at all possible: users may deliberately set an unusual timezone, and furthermore are likely to know what they actually want better than our timezone database does.)
	offset: The current timezone offset in hours from GMT.
	currently: A data point (see below) containing the current weather conditions at the requested location.
	minutely: A data block (see below) containing the weather conditions minute-by-minute for the next hour. (This property’s name should be read as an adjective—analogously to “hourly” or “daily” and meaning “reckoned by the minute”—rather than as an adverb meaning “meticulously.” Yes, we know that this is not proper English. No, we will not change it. Complaints to this effect will be deleted with utmost prejudice.)
	hourly: A data block (see below) containing the weather conditions hour-by-hour for the next two days.
	daily: A data block (see below) containing the weather conditions day-by-day for the next week.
	alerts: An array of alert objects (see below), which, if present, contains any severe weather alerts, issued by a governmental weather authority, pertinent to the requested location.
	flags: An object containing miscellaneous metadata concerning this request. (See flags object, below.)
	*/

	// Pebble:
		//[lat],[lon]?units=[uni]&exclude=hourly,daily,alerts

	public class Client
	{
		public float latitude;
		public float longitude;
		public ForecastIO.Unit unit;
		public string exclude;
		public string extend;
		public string time;
	}
}

Weather/Models/Pebble.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ForecastIO;

namespace Weather.Models
{
	public class Pebble
	{
		public Pebble(Models.Client client)
		{
			//42.25889,-85.67750
			var extendBlocks = new Extend[] 
			{
				
			};
			var excludeBlocks = new Exclude[] 
			{
				Exclude.hourly,
				Exclude.daily
			};
			var request = new ForecastIORequest("", client.latitude, client.longitude, DateTime.Now, client.unit, extendBlocks, excludeBlocks);
			var response = request.Get();

			Icons.TryGetValue(response.currently.icon, out Icon);
			Temp = response.currently.temperature;


		}

		public int Icon;
		public float Temp;
		//public 

		private Dictionary<string, int> _icons;
		public Dictionary<string, int> Icons
		{
			get
			{
				if (_icons == null)
				{
					_icons = new Dictionary<string, int>();
					_icons.Add("clear-day", 0);
					_icons.Add("clear-night", 1);
					_icons.Add("rain", 2);
					_icons.Add("snow", 3);
					_icons.Add("sleet", 4);
					_icons.Add("wind", 5);
					_icons.Add("fog", 6);
					_icons.Add("cloudy", 7);
					_icons.Add("partly-cloudy-day", 8);
					_icons.Add("partly-cloudy-night", 9);
				}

				return _icons;
			}
		}
	}
}

Weather/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Weather.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }
    }
}

Weather/Controllers/WeatherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ForecastIO;

namespace Weather.Controllers
{
    public class WeatherController : Controller
    {
        //
        // GET: /Weather/

        public ViewResult Pebble()
        {
			// /Weather/Pebble?lat=42.25889f&lon=-85.67750f
			string lat = Request.QueryString["lat"].ToString();
			string lon = Request.QueryString["lon"].ToString();

	        var client = new Models.Client();
			client.latitude = (float)Convert.ToDouble(lat); //42.25889f;
			client.longitude = (float)Convert.ToDouble(lon); //-85.67750f;
			client.unit = Unit.us; // need to figure out how to parse from query string

	        var pebble = new Models.Pebble(client);

			return View(pebble);
        }
    }
}

Weather/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
JSON GET
<ul>
    <li>@Html.ActionLink("Pebble:", "Pebble", "Weather") <a href="/Weather/Pebble?lat=42.25889&lon=-85.67750">Data</a>   @Html.ActionLink("Pebble:", "Pebble", "Weather").ToHtmlString()</li>
    
</ul>

Weather/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>

    </head>
    <body>
        <header>
        </header>
        <div id="body">
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>
    </body>
</html>

Weather/Views/Weather/Pebble.cshtml
@model Weather.Models.Pebble

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Pebble</title>
</head>
<body>
    <div>
        
        @Html.LabelFor(model => model.Temp): @Html.DisplayFor(model => model.Temp)<br/>
        @Html.LabelFor(model => model.Icon): @Html.DisplayFor(model => model.Icon)
    </div>
</body>
</html>